__1. Найти с помощью NumPy SVD для матрицы__

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

__Решение:__

In [44]:
import numpy as np


matrix = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
print(matrix)

U, s, W = np.linalg.svd(matrix)

V = W.T


D = np.zeros_like(matrix, dtype=float)
D[np.diag_indices(min(matrix.shape))] = s


[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


__2. Для матрицы из предыдущего задания найти:__

    а) евклидову норму;
    
    б) норму Фробениуса.

__а) евклидову норму__

In [45]:
D[0,0]

8.824868854820442

__б) норму Фробениуса__

In [46]:
print(np.sqrt(sum(s ** 2)))

11.045361017187261
