__1.__ Установить, какие произведения матриц  𝐴𝐵  и  𝐵𝐴  определены, и найти размерности полученных матриц:

а)  𝐴  — матрица  4×2 ,  𝐵  — матрица  4×2 ;

б)  𝐴  — матрица  2×5 ,  𝐵  — матрица  5×3 ;

в)  𝐴  — матрица  8×3 ,  𝐵  — матрица  3×8 ;

г)  𝐴  — квадратная матрица  4×4 ,  𝐵  — квадратная матрица  4×4 .

__Решение__

а) произведения не пределены по определению

б) Определено АВ размерность 2×3, ВА - не определенно

в) Определено АВ и ВА размерность 8×8 и 3×3

г) Определено АВ и ВА размерность 4×4 и 4×4

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__Решение__:
    
 $A+B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$+$\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

 $A+B = \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot$ $\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [8]:
import numpy as np
print(np.array([[1, -2],[3, 0]]) + np.array([[4, -1],[0, 5]]))
print()
print(np.dot(np.array([[1, -2],[3, 0]]),np.array([[4, -1],[0, 5]])))

[[ 5 -3]
 [ 3  5]]

[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

__Решение__:

$3A-2B+4C$ =$\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$ - $\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$ + $\begin{pmatrix}
8 & -16\\ 
4 & -4
\end{pmatrix}$ = $\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [13]:
import numpy as np
print(3 * np.array([[1, 7],[3, -6]]) - 2 * np.array([[0, 5],[2, -1]]) + 4 * np.array([[2, -4],[1, 1]]))

[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

__Решение__:

$ \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} \cdot$ 
$\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$ = $\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13\\ 
\end{pmatrix}$

$\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}  \cdot$
$ \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$ 
 = $\begin{pmatrix}
45 & 0\\ 
0 & 14\\ 
\end{pmatrix}$

In [12]:
import numpy as np
A = np.array([[4, 1], [5, -2], [2, 3]])
print(np.dot(A, A.T))
print()
print(np.dot(A.T, A))

[[17 18 11]
 [18 29  4]
 [11  4 13]]

[[45  0]
 [ 0 14]]


__5*__. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [151]:
from collections import Counter


A = [[1, 3], [1, 0]]
B = [[2, 1], [3, 0]]



def multiply_matrix(a, b):
    rezult_first = []
    rezult = []
    c = []
    prov_1 = []
    prov_2 = []
    for i in a:
        prov_1.append(len(i))
    for i in b:
        prov_2.append(len(i))
    if len(Counter(prov_1).most_common()) > 1:
        print(f'Матрица {a} задана некорректно')
    elif len(Counter(prov_2).most_common()) > 1:
        print(f'Матрица {b} задана некорректно')
    elif not a or not b:
        print('Одна из матриц пустая')
    elif len(a) != len(b[0]):
        print('Умножение матриц таких размернстей не определено')
    else:
        for t, l in enumerate(a):
            for i, j in enumerate(b):
                for k, q in enumerate(l):
                    c.append(q * b[k][i])
                rezult_first.append(sum(c))
                c = []
            rezult.append(rezult_first)
            
            rezult_first = []
            
        return rezult 
                        
multiply_matrix(A, B)       

[[11, 1], [2, 1]]

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

__Решение__:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = \sin{x} \cdot \sin{x}  + \cos{x} \cdot \cos{x} = 1$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 \cdot 5 \cdot 9 + 0 \cdot 2 \cdot 9 + 0 \cdot 0 \cdot 3 - 3 \cdot 5 \cdot 0 - 9 \cdot 2 \cdot 0 - 4 \cdot 1 \cdot 0 = 180$$

   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1 \cdot 5 \cdot 9 + 7 \cdot 2 \cdot 6 + 3 \cdot 4 \cdot 8 - 3 \cdot 5 \cdot 7 - 9 \cdot 2 \cdot 4 - 1 \cdot 6 \cdot 8 = 0$$

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

__Решение__:

а) По свойству определителля $det(A^{2}) = det(A) \cdot det(A) = 4 \cdot 4 = 16$

б) По свойству определителля $det(A^{T}) = det(A) = 4$

в) $det(2A) = 8$ определитель увеличивается в 4 раза в данном случаe, т.е значение определителя будет увеличиваться на коэффициент возведенный в квадрат 

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__Решение__:

$$\det{\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}} = -2 \cdot -14 \cdot 13 + -3 \cdot 7 \cdot 6 + -3 \cdot 7 \cdot 4 + 3\cdot 3 \cdot 14 - 4\cdot 7 \cdot 13 +  2\cdot 6 \cdot 7 = 0 \Rightarrow$$ матрица вырожденная

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

__Решение__:
    
   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix} \sim \begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
0 & 1 & 2
\end{pmatrix} \sim \begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
0 & 1 & 2
\end{pmatrix} \sim \begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
0 & 0 & 0
\end{pmatrix} \Rightarrow$ ранг равен 2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix} \sim \begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & -2 & -1\\ 
2 & 3 & 5 & 6
\end{pmatrix} \begin{pmatrix}
0 & 0 & 0 & 0\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & -2 & -1\\ 
2 & 3 & 5 & 6
\end{pmatrix}\Rightarrow$ ранг равен 3